### PR TITLE
Move to 1ES build pools

### PR DESCRIPTION
**Pull request by JoeRobich**

### CODE REVIEW

**Review by tmat — APPROVED** [review]

**Comment by JoeRobich** [comment]
@tmat got a failing test build and not sure why it can't find the SDK - https://dev.azure.com/dnceng/internal/_build/results?buildId=1396505&view=logs&j=7c8326b9-0a5f-532a-e6de-db8515c72d9a&t=6b204277-d195-526a-8566-4eab1bd588e9 (microsoft)

**Comment by JoeRobich** [comment]
@jonfortescue Ran a [test build with these changes](https://dev.azure.com/dnceng/internal/_build/results?buildId=1396505&view=logs&j=7c8326b9-0a5f-532a-e6de-db8515c72d9a&t=6b204277-d195-526a-8566-4eab1bd588e9) and the build is failing saying that no SDKs are installed. Have you seen similar issues when making the change?

**Comment by tmat** [comment]
> @tmat got a failing test build and not sure why it can't find the SDK - https://dev.azure.com/dnceng/internal/_build/results?buildId=1396505&view=logs&j=7c8326b9-0a5f-532a-e6de-db8515c72d9a&t=6b204277-d195-526a-8566-4eab1bd588e9 (microsoft)

No idea :(

**Comment by JoeRobich** [comment]
@tmat If we set the SDK version in the global.json, it installs and [builds fine](https://dev.azure.com/dnceng/internal/_build/results?buildId=1396793&view=results). Let me know if you want to handle this differently.

**Review by tmat — APPROVED** [review]

**Pull request merged**
