### PR TITLE
Back to VSSDK 15.0.26201-alpha

### PR DESCRIPTION
**Pull request by tmat**
15.0.26507-alpha isn't compatible with 15.3 P1

### CODE REVIEW

**Comment by tmat** [comment]
test prtest/windows/debug please

**Comment by jaredpar** [comment]
Why did you have to move back?

**Comment by tmat** [comment]
Getting loader exceptions:

```
Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.LoaderExceptions: 
      Could not load type 'Microsoft.VisualStudio.Text.Adornments.StructureAdornmentStyle' from assembly 'Microsoft.VisualStudio.Text.UI, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
```

**Comment by jaredpar** [comment]
Ah yes.  Saw that last night.  It looks like they moved that type from MS.VS.Text.UI.WPF to MS.VS.Text.UI.  I imagine that's going to be painful for a number of people.

**Comment by tmat** [comment]
test prtest/windows/debug  please

**Pull request merged**
