### PR TITLE
Feed cleanup

### PR DESCRIPTION
**Pull request by mmitche**
Switch away from blob feeds.

### CODE REVIEW

**Comment by tmat** [comment]
It seems we don't have `MicroBuild.Plugins.SwixBuild` published in the feed. This is needed to build VS components inserting to VS.
It would probably be better if this package was pushed to `https://pkgs.dev.azure.com/azure-public/vside/_packaging/vs-impl/nuget/v3/index.json`

**Comment by mmitche** [comment]
> It seems we don't have `MicroBuild.Plugins.SwixBuild` published in the feed. This is needed to build VS components inserting to VS.
> It would probably be better if this package was pushed to `https://pkgs.dev.azure.com/azure-public/vside/_packaging/vs-impl/nuget/v3/index.json`

Cool ya.  I think I can also push it to dotnet-eng.

**Comment by tmat** [comment]
Actually, dotnet-eng would make more sense. Let's do that.

**Comment by mmitche** [comment]
> Actually, dotnet-eng would make more sense. Let's do that.

Kind of surprised it's not there already

**Comment by mmitche** [comment]
Pushed package
/azp run

**Comment by mmitche** [comment]
Pushed packages

**Pull request merged**
