### PR TITLE
Remove use of Microsoft.VisualStudio.Text.Internal

### PR DESCRIPTION
**Pull request by jasonmalinowski**
Fixes https://github.com/dotnet/interactive-window/issues/126

### CODE REVIEW

**Comment by tmat** [comment]
@genlu Do we still need the hack that's making the PR validation fail?

**Review by tmat — APPROVED** [review]

**Comment by genlu** [comment]
@tmat Unfortunately yes. If this needs to go in dev16, then we need to create a dev16 branch w/o all the dev17 changes

**Comment by jasonmalinowski** [comment]
@genlu this doesn't _need_ to go into Dev16 (it's just generic cleanup in support of a larger Roslyn change). But if I wait for Dev17, how long do I have to wait until this is sorted out? I know I'm asking you to predict a schedule, but is that expected to be on the order of weeks or months?

**Comment by genlu** [comment]
@jasonmalinowski If you are asking when can we get rid of the internal feed, then I'm still hoping it will happen some time this week

**Comment by jasonmalinowski** [comment]
@genlu I guess though am I allowed to merge this for 17.0 Preview 1, or is that still being reserved for 64-bit changes only?

**Comment by genlu** [comment]
You can merge now, it's just that there's no way for your to test your change since we don't have VS with new interops yet.

**Pull request merged**
