### PR TITLE
dev17 setup authoring fix

### PR DESCRIPTION
**Pull request by genlu**
This change is required for package with new interops

### CODE REVIEW

**Comment by genlu** [comment]
No longer needed based on latest guideline

**Review by sharwell — APPROVED** [review]

**Comment by genlu** [comment]
@JoeRobich hmm, seems "merge" button is available even when CI's not completed

image

**Comment by JoeRobich** [comment]
> hmm, seems "merge" button is available even when CI's not completed

@genlu There is are no required checks for the main branch. @tmat Should I make an approval and passing CI required?

**Comment by genlu** [comment]
Also the build was queued almost 2 hours ago but still not started yet. We might need to find a better pool :(

**Pull request merged**
