### PR TITLE
Fix crash in the fix for "Part of the fix for #37: Accessibility: Narrator issues (#45)

### PR DESCRIPTION
**Pull request by AlexanderSher**
Accessibility fix. We had to back out the previous fix as it was causing crashes.

### CODE REVIEW

**Comment by tmat** [comment]
:shipit:

**Comment by tmat** [comment]
@MattGertz for approval.

**Comment by MattGertz** [comment]
@tmat The repo is missing the following labels, so I cannot proceed:

Pending director approval
Pending Shiproom approval
Approved to merge

And I don't seem to have permission to add them.  Can you add these labels and then tag me?

**Comment by tmat** [comment]
@MattGertz Labels added.

**Comment by MattGertz** [comment]
@tmat Hmm, I still don't have permission to use the labels.  Can you add MattGertz to the appropriate group?

**Comment by tmat** [comment]
@MattGertz added you to the collaborators. Does it work now?

**Comment by MattGertz** [comment]
Yep, thank you!

**Pull request merged**
